name: Report a bug
description: Report a bug with GlyphVisualizer
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
      description: Fill all fields even if you think it is irrelevant for the issue
      options:
        - label: I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
          required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes:
      options:
        - label: I've verified that I have **updated GlyphVisualizer to the latest release version** ([latest version](https://github.com/SebiAi/GlyphVisualizer/releases/latest))
          required: true
        - label: I've searched [known issues](https://github.com/SebiAi/GlyphVisualizer/issues?q=label%3Abug) and the [roadmap](https://github.com/users/SebiAi/projects/5) for similar issues **including closed ones**. DO NOT post duplicates
          required: true
  - type: textarea
    id: description
    attributes:
      label: Provide a description that is worded well enough to be understood
      placeholder: |
        Provide any additional information, any suggested solutions, and as much context and examples as possible. Keep in mind that uploading copyright protected songs is not a good idea.
    validations:
      required: true
  - type: checkboxes
    id: verbose
    attributes:
      label: Provide verbose output that clearly demonstrates the problem
      options:
        - label: Run GlyphVisualizer with **--verbose** flag added (`GlyphVisualizer --verbose`) - adjust name of the executable accordingly ([Open command prompt on windows](https://www.lifewire.com/open-command-prompt-in-a-folder-5185505))
          required: true
        - label: Copy the WHOLE output (starting with `Main.Verbose: Verbose logging activated`) and insert it below
          required: true
  - type: textarea
    id: log
    attributes:
      label: Complete Verbose Output
      description: |
        It should start like this:
      placeholder: |
        Main.Verbose: Verbose logging activated
        Main.Verbose: Current software version: VERSION_HERE
        Main.Verbose: Current software git hash: GIT_COMMIT_HASH_HERE
        <more lines>
      render: shell
    validations:
      required: true
