name: Feature request
description: Request a new functionality
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
      description: Fill all fields even if you think it is irrelevant for the issue
      options:
        - label: I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
          required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes:
      options:
        - label: I've looked through the [README](https://github.com/SebiAi/GlyphVisualizer#readme)
          required: true
        - label: I've verified that I have **updated GlyphVisualizer to the latest release version** ([latest version](https://github.com/SebiAi/GlyphVisualizer/releases/latest))
          required: true
        - label: I've searched [known issues](https://github.com/SebiAi/GlyphVisualizer/issues?q=label%3Aenhancement) and the [roadmap](https://github.com/users/SebiAi/projects/5) for similar issues **including closed ones**. DO NOT post duplicates
          required: true
  - type: textarea
    id: description
    attributes:
      label: Provide a description that is worded well enough to be understood
      placeholder: Provide any additional information, any suggested solutions, and as much context and examples as possible
    validations:
      required: true
