/*
This file is part of the GlyphVisualizer project, a Glyph composition
player that plays Glyph compositions from Nothing phones.
Copyright (C) 2025  Sebastian Aigner (aka. SebiAi)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#ifndef GV_PHONE3CONFIGURATION_H
#define GV_PHONE3CONFIGURATION_H

#include "IConfiguration.h"

class Phone3Configuration : public IConfiguration {
private:
    // Contains all indexes that can be displayed with the glyph matrix.
    // Order is important because of the mapping taking place later!!!
    static constexpr qsizetype validColorIndexes[489] = {
        9,10,11,12,13,14,15,32,33,34,35,36,37,38,39,40,41,42,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,79,80,81,82,83,84,85,86,
        87,88,89,90,91,92,93,94,95,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,127,128,129,130,131,
        132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,
        167,168,169,170,171,172,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,201,202,
        203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,225,226,227,228,229,230,231,232,233,234,
        235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,
        266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,
        297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,
        328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,
        359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,
        390,391,392,393,394,395,396,397,398,399,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,
        422,423,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,452,453,454,455,456,457,
        458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,
        493,494,495,496,497,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,529,530,531,532,533,534,535,
        536,537,538,539,540,541,542,543,544,545,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,582,583,584,585,586,587,
        588,589,590,591,592,609,610,611,612,613,614,615
    };

public:
    static constexpr DeviceBuild staticBuild = DeviceBuild::Metroid;

    Phone3Configuration(const QColor& fallbackColor): IConfiguration{
        fallbackColor,
        QList<Glyph>{
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_9")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_10")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_11")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_12")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_13")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_14")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_15")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_32")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_33")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_34")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_35")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_36")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_37")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_38")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_39")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_40")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_41")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_42")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_55")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_56")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_57")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_58")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_59")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_60")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_61")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_62")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_63")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_64")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_65")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_66")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_67")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_68")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_69")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_79")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_80")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_81")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_82")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_83")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_84")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_85")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_86")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_87")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_88")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_89")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_90")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_91")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_92")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_93")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_94")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_95")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_103")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_104")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_105")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_106")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_107")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_108")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_109")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_110")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_111")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_112")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_113")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_114")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_115")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_116")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_117")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_118")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_119")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_120")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_121")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_127")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_128")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_129")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_130")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_131")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_132")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_133")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_134")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_135")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_136")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_137")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_138")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_139")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_140")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_141")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_142")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_143")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_144")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_145")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_146")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_147")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_152")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_153")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_154")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_155")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_156")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_157")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_158")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_159")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_160")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_161")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_162")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_163")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_164")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_165")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_166")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_167")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_168")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_169")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_170")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_171")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_172")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_176")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_177")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_178")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_179")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_180")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_181")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_182")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_183")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_184")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_185")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_186")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_187")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_188")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_189")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_190")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_191")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_192")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_193")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_194")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_195")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_196")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_197")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_198")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_201")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_202")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_203")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_204")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_205")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_206")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_207")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_208")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_209")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_210")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_211")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_212")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_213")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_214")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_215")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_216")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_217")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_218")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_219")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_220")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_221")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_222")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_223")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_225")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_226")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_227")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_228")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_229")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_230")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_231")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_232")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_233")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_234")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_235")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_236")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_237")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_238")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_239")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_240")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_241")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_242")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_243")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_244")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_245")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_246")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_247")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_248")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_249")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_250")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_251")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_252")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_253")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_254")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_255")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_256")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_257")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_258")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_259")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_260")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_261")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_262")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_263")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_264")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_265")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_266")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_267")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_268")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_269")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_270")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_271")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_272")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_273")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_274")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_275")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_276")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_277")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_278")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_279")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_280")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_281")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_282")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_283")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_284")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_285")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_286")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_287")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_288")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_289")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_290")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_291")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_292")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_293")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_294")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_295")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_296")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_297")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_298")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_299")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_300")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_301")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_302")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_303")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_304")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_305")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_306")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_307")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_308")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_309")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_310")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_311")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_312")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_313")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_314")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_315")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_316")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_317")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_318")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_319")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_320")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_321")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_322")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_323")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_324")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_325")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_326")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_327")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_328")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_329")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_330")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_331")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_332")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_333")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_334")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_335")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_336")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_337")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_338")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_339")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_340")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_341")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_342")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_343")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_344")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_345")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_346")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_347")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_348")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_349")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_350")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_351")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_352")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_353")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_354")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_355")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_356")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_357")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_358")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_359")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_360")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_361")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_362")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_363")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_364")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_365")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_366")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_367")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_368")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_369")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_370")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_371")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_372")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_373")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_374")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_375")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_376")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_377")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_378")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_379")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_380")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_381")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_382")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_383")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_384")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_385")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_386")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_387")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_388")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_389")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_390")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_391")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_392")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_393")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_394")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_395")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_396")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_397")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_398")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_399")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_401")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_402")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_403")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_404")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_405")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_406")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_407")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_408")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_409")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_410")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_411")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_412")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_413")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_414")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_415")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_416")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_417")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_418")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_419")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_420")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_421")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_422")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_423")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_426")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_427")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_428")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_429")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_430")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_431")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_432")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_433")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_434")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_435")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_436")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_437")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_438")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_439")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_440")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_441")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_442")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_443")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_444")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_445")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_446")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_447")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_448")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_452")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_453")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_454")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_455")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_456")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_457")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_458")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_459")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_460")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_461")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_462")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_463")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_464")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_465")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_466")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_467")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_468")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_469")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_470")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_471")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_472")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_477")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_478")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_479")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_480")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_481")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_482")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_483")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_484")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_485")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_486")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_487")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_488")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_489")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_490")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_491")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_492")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_493")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_494")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_495")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_496")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_497")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_503")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_504")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_505")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_506")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_507")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_508")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_509")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_510")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_511")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_512")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_513")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_514")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_515")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_516")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_517")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_518")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_519")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_520")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_521")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_529")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_530")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_531")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_532")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_533")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_534")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_535")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_536")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_537")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_538")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_539")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_540")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_541")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_542")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_543")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_544")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_545")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_555")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_556")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_557")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_558")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_559")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_560")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_561")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_562")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_563")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_564")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_565")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_566")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_567")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_568")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_569")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_582")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_583")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_584")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_585")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_586")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_587")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_588")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_589")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_590")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_591")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_592")},

            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_609")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_610")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_611")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_612")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_613")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_614")},
            Glyph{QStringLiteral(":/glyphs/phone3/matrix"), Glyph::Reference::CENTERED, QPointF{0, 0}, QStringLiteral("path_615")},
        },
        Phone3Configuration::staticBuild,
        QList<qsizetype>({625}),
        QSize{170, 170},
        QList<MySvgRenderer>{
            Glyph{QStringLiteral(":/glyphs/phone3/matrix_background"), Glyph::Reference::CENTERED, QPointF{0, 0}},
        }
    } { }

    virtual IConfiguration* clone() const override {
        return new Phone3Configuration{*this};
    }

protected:
    virtual void renderPrivate(QPainter& painter, const QList<QColor>& colors) override {
        static constexpr qsizetype validColorIndexesSize = sizeof(validColorIndexes)/sizeof(validColorIndexes[0]);
        static QList<QColor> validColors(validColorIndexesSize);

        // Map to a new array that can then be directly mapped to the glyphs
        // with the base function
        for (qsizetype i = 0; i < validColorIndexesSize; ++i) {
            validColors[i] = colors.at(validColorIndexes[i]);
        }

        IConfiguration::renderPrivate(painter, validColors);
    }
};

#endif // GV_PHONE3CONFIGURATION_H
