name: Build Linux Appimage

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: docker-publish-group
  cancel-in-progress: false

jobs:
  build:
    name: Build Linux Appimage
    runs-on: ubuntu-latest
    container: ghcr.io/sebiai/glyphvisualizer-linux-appimage-qt6-build-container:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Avoids the error: "fatal: detected dubious ownership in repository at '...'"
      - name: Configure safe directory for git
        run: git config --global --add safe.directory '*'

      - name: Build and package
        run: |
            /bin/bash -c "./devscripts/clean-build.sh"
            /bin/bash -c "./devscripts/make-appimage.sh"

      - name: Get version from CMakeLists.txt
        id: get_version
        run: |
          echo "version=v$(grep -oP 'project\(GlyphVisualizer VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GlyphVisualizer-${{ steps.get_version.outputs.version }}_linux-ubuntu-x64
          path: |
            ./build/GlyphVisualizer*_linux-ubuntu-x64.AppImage
            ./build/GlyphVisualizer*_linux-ubuntu-x64.AppImage.zsync
            ./build/GlyphVisualizer*_linux-ubuntu-x64.AppImage.sha256
