name: Build MacOS DMG

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build MacOS DMG
    strategy:
      matrix:
        os: [macos-14-large, macos-14-xlarge]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Determine architecture
        id: determine_architecture
        run: |
          MACHINE_ARCH=$(uname -m)
          if [[ "${MACHINE_ARCH}" == "x86_64" ]]; then
            echo "Running on x86_64 architecture."
          elif [[ "${MACHINE_ARCH}" == "arm64" ]]; then
            echo "Running on arm64 architecture."
          else
            echo "Unsupported architecture: ${MACHINE_ARCH}"
            exit 1
          fi
          echo "arch=${MACHINE_ARCH}" >> $GITHUB_OUTPUT

      # Install build dependencies
      - name: Install Qt6.8.3
        uses: jurplel/install-qt-action@v4
        with:
          # See https://ddalcino.github.io/aqt-list-server/
          aqtversion: '==3.1.*'
          version: '6.8.3'
          modules: 'qtmultimedia'
          cache: true
          cache-key-prefix: install-qt-6.8.3-action-${{ runner.os }}
      - name: Install Ninja Build System
        run: brew install ninja

      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build and package
        run: |
            /bin/bash -c "./devscripts/clean-build.sh"
            /bin/bash -c "./devscripts/make-dmg.sh"

      - name: Get version from CMakeLists.txt
        id: get_version
        run: |
          echo "version=v$(grep -oE 'project\(GlyphVisualizer VERSION [0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GlyphVisualizer-${{ steps.get_version.outputs.version }}_macOS-14-${{ steps.determine_architecture.outputs.arch }}
          path: |
            ./build/GlyphVisualizer*_macOS-14-${{ steps.determine_architecture.outputs.arch }}.dmg
            ./build/GlyphVisualizer*_macOS-14-${{ steps.determine_architecture.outputs.arch }}.dmg.sha256
